export const data = [  
    {  
       Name:'Arshan',
       Gender:'Male',
       Physics:88,
       Math:87,
       English:78
    },
    {  
       Name:'Ali',
       Gender:'Male',
       Physics:96,
       Math:100,
       English:95
    },
    {  
       Name:'Usama',
       Gender:'Male',
       Physics:89,
       Math:90,
       English:70
    },
    {  
       Name:'Qasim',
       Gender:'Male',
       Physics:30,
       Math:25,
       English:40
    },
    {  
       Name:'Hassan',
       Gender:'Male',
       Physics:56,
       Math:46,
       English:78,
    },
    {  
       Name:'Amir',
       Gender:'Male',
       Physics:12,
       Math:67,
       English:67
    },
    {  
       Name:'Ansar',
       Gender:'Male',
       Physics:78,
       Math:71,
       English:67
    },
    {  
       Name:'Yasir',
       Gender:'Male',
       Physics:56,
       Math:45,
       English:67
    }

    
 ]